export const PermissionsEnum = Object.freeze({
  CATEGORY_INDEX: 'category.index',
  CATEGORY_ADD: 'category.add',
  CATEGORY_UPDATE: 'category.update',
  CATEGORY_ACTIVE: 'category.active',
  CATEGORY_DELETE: 'category.delete',

  REORDER: 'reorder',

  ITEM_INDEX: 'item.index',
  ITEM_ADD: 'item.add',
  ITEM_UPDATE: 'item.update',
  ITEM_ACTIVE: 'item.active',
  ITEM_DELETE: 'item.delete',
  
  // INFO_ADMIN_UPDATE: 'info_admin.update',
  // INFO_ADMIN_SHOW_BY_ID: 'info_admin.show_by_id',
  UPDATE_RESTAURANT_ADMIN: 'update_restaurant_admin',
  ORDER_INDEX: 'order.index',
  ORDER_ADD: 'order.add',
  ORDER_UPDATE: 'order.update',
  // ORDER_SHOW_BY_ID: 'order.show_by_id',
  ORDER_DELETE: 'order.delete',
  USER_INDEX: 'user.index',
  USER_ADD: 'user.add',
  USER_UPDATE: 'user.update',
  // USER_SHOW_BY_ID: 'user.show_by_id',
  USER_DELETE: 'user.delete',
  USER_ACTIVE: 'user.active',
  ADVERTISEMENT_INDEX: 'advertisement.index',
  ADVERTISEMENT_ADD: 'advertisement.add',
  ADVERTISEMENT_UPDATE: 'advertisement.update',
  // ADVERTISEMENT_SHOW_BY_ID: 'advertisement.show_by_id',
  ADVERTISEMENT_DELETE: 'advertisement.delete',
  NEWS_INDEX: 'news.index',
  NEWS_ADD: 'news.add',
  NEWS_UPDATE: 'news.update',
  // NEWS_SHOW_BY_ID: 'news.show_by_id',
  NEWS_DELETE: 'news.delete',
  RATE_INDEX: 'rate.index',
  EXCEL: 'excel',
  NOTIFICATIONS_INDEX: 'notifications.index',
  TABLE_INDEX: 'table.index',
  TABLE_ADD: 'table.add',
  TABLE_UPDATE: 'table.update',
  // TABLE_SHOW_BY_ID: 'table.show_by_id',
  TABLE_DELETE: 'table.delete',
  RESTAURANT_ID: 'restaurantId',
  MY_RESTAURANTS: 'my_restaurants',
  SERVICE_INDEX:'service.index',
  SERVICE_ADD:'service.add',
  SERVICE_UPDATE:'service.update',
  SERVICE_DELETE:'service.delete',
  DELIVERY_INDEX:'delivery.index',
  DELIVERY_ADD:'delivery.add',
  DELIVERY_UPDATE:'delivery.update',
  DELIVERY_DELETE:'delivery.delete',
  DELIVERY_ACTIVE:'delivery.active'
});

export const SuperPermissionsEnum = Object.freeze({
  CITY_INDEX: 'city.index',
  CITY_ADD: 'city.add',
  CITY_UPDATE: 'city.update',
  CITY_ACTIVE: 'city.active',
  CITY_DELETE: 'city.delete',
  // CITY_SHOW_BY_ID: 'city.show_by_id',
  SUPER_ADMIN_INDEX: 'super_admin.index',
  SUPER_ADMIN_ADD: 'super_admin.add',
  SUPER_ADMIN_UPDATE: 'super_admin.update',
  SUPER_ADMIN_ACTIVE: 'super_admin.active',
  SUPER_ADMIN_DELETE: 'super_admin.delete',
  // SUPER_ADMIN_SHOW_BY_ID: 'super_admin.show_by_id',
  MENU_INDEX: 'menu.index',
  MENU_ADD: 'menu.add',
  MENU_ACTIVE: 'menu.active',
  MENU_DELETE: 'menu.delete',
  // MENU_SHOW_BY_ID: 'menu.show_by_id',
  EMOJI_INDEX: 'emoji.index',
  EMOJI_ADD: 'emoji.add',
  EMOJI_UPDATE: 'emoji.update',
  EMOJI_ACTIVE: 'emoji.active',
  EMOJI_DELETE: 'emoji.delete',
  // EMOJI_SHOW_BY_ID: 'emoji.show_by_id',
  RESTAURANT_INDEX: 'restaurant.index',
  RESTAURANT_ADD: 'restaurant.add',
  RESTAURANT_UPDATE: 'restaurant.update',
  RESTAURANT_ACTIVE: 'restaurant.active',
  RESTAURANT_DELETE: 'restaurant.delete',
  RESTAURANT_UPDATE_SUPER_ADMIN_RESTAURANT_ID: 'restaurant.update_super_admin_restaurant_id',
  PACKAGE_INDEX: 'package.index',
  PACKAGE_ADD: 'package.add',
  PACKAGE_UPDATE: 'package.update',
  // PACKAGE_SHOW_BY_ID: 'package.show_by_id',
  PACKAGE_ACTIVE: 'package.active',
  PACKAGE_DELETE: 'package.delete',
  PACKAGE_ADD_SUBSCRIPTION: 'package.add_subscription',
  PACKAGE_SHOW_RESTAURANT_SUBSCRIPTION: 'package.show_restaurant_subscription',
  RATE_INDEX: 'rate.index',
  EXCEL: 'excel',
  RESTAURANT_SHOW_BY_ID: 'restaurant.show_by_id',
  // UPDATE_SUPER_ADMIN_UPDATE: 'update_super_admin.update',
  ADMIN_RESTAURANT_INDEX: 'admin_restaurant.index',
  ADMIN_RESTAURANT_ADD: 'admin_restaurant.add',
  ADMIN_RESTAURANT_UPDATE: 'admin_restaurant.update',
  ADMIN_RESTAURANT_ACTIVE: 'admin_restaurant.active',
  ADMIN_RESTAURANT_DELETE: 'admin_restaurant.delete',
  // ADMIN_RESTAURANT_SHOW_BY_ID: 'admin_restaurant.show_by_id',
  RESTAURANT_MANAGER_INDEX: 'restaurant_manager.index',
  RESTAURANT_MANAGER_ADD: 'restaurant_manager.add',
  
  RESTAURANT_MANAGER_UPDATE: 'restaurant_manager.update',
  RESTAURANT_MANAGER_DELETE: 'restaurant_manager.delete',
  RESTAURANT_MANAGER_ACTIVE: 'restaurant_manager.deactivat',


  CATEGORY_INDEX: 'category.index',
  CATEGORY_ADD: 'category.add',
  CATEGORY_UPDATE: 'category.update',
  CATEGORY_ACTIVE: 'category.active',
  CATEGORY_DELETE: 'category.delete',
  REORDER: 'reorder',
  ITEM_INDEX: 'item.index',
  ITEM_ADD: 'item.add',
  ITEM_UPDATE: 'item.update',
  ITEM_ACTIVE: 'item.active',
  ITEM_DELETE: 'item.delete',
  USER_INDEX: 'user.index',
  USER_ADD: 'user.add',
  USER_UPDATE: 'user.update',
  // USER_SHOW_BY_ID: 'user.show_by_id',
  USER_DELETE: 'user.delete',
  USER_ACTIVE: 'user.active',
  ADVERTISEMENT_INDEX: 'advertisement.index',
  ADVERTISEMENT_ADD: 'advertisement.add',
  ADVERTISEMENT_UPDATE: 'advertisement.update',
  // ADVERTISEMENT_SHOW_BY_ID: 'advertisement.show_by_id',
  ADVERTISEMENT_DELETE: 'advertisement.delete',
  NEWS_INDEX: 'news.index',
  NEWS_ADD: 'news.add',
  NEWS_UPDATE: 'news.update',
  // NEWS_SHOW_BY_ID: 'news.show_by_id',
  NEWS_DELETE: 'news.delete',
  TABLE_INDEX: 'table.index',
  TABLE_ADD: 'table.add',
  TABLE_UPDATE: 'table.update',
  // TABLE_SHOW_BY_ID: 'table.show_by_id',
  TABLE_DELETE: 'table.delete',
  RESTAURANTID: 'restaurantId',
  MY_RESTAURANTS: 'my_restaurants',
  LOGS: 'logs'
});